// SPDX-License-Identifier: Apache-2.0

export enum Fields {
  PROCESSING_DATE_TIME = 0,
  MESSAGE_ID = 1,
  TRANSACTION_TYPE = 2,
  PAYMENT_CURRENCY_CODE = 3,
  TOTAL_PAYMENT_AMOUNT = 4,
  SENDER_NAME = 5,
  RECEIVER_NAME = 6,
  SENDER_AGENT_SPID = 7,
  RECEIVER_AGENT_SPID = 8,
  SENDER_ACCOUNT = 9,
  RECEIVER_ACCOUNT = 10,
  REPORTING_CODE = 11,
}
