// SPDX-License-Identifier: Apache-2.0

export enum Fields {
  PROCESSING_DATE_TIME = 0,
  MESSAGE_ID = 1,
  TRANSACTION_TYPE = 2,
  PAYMENT_CURRENCY_CODE = 3,
  TOTAL_PAYMENT_AMOUNT = 4,
  SENDER_ID = 5,
  SENDER_NAME = 6,
  RECEIVER_ID = 7,
  RECEIVER_NAME = 8,
  SENDER_AGENT_SPID = 9,
  RECEIVER_AGENT_SPID = 10,
  SENDER_ACCOUNT = 11,
  RECEIVER_ACCOUNT = 12,
  REPORTING_CODE = 13,
}
